---
abstract: "Perl client library for SeatGeek's Sixpack A/B testing framework http://sixpack.seatgeek.com/"
author:
  - 'Menno Blom <blom@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Sixpack
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::UUID: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  URI: 0
  perl: 5.006
resources:
  repository: https://github.com/b10m/p5-WWW-Sixpack
version: 0.02
